name: project3
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: project3
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  NODE_ENV: testGithub

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_HOST: ${{env.POSTGRES_HOST}}
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: ./express-server
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install 
          yarn playwright install-deps
          yarn knex migrate:latest --env testGithub
          yarn jest --run-in-band

  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd c25-bad-project-04-tw
            git pull origin production
            cd express-server
            yarn install
            yarn knex migrate:rollback --env production
            yarn knex migrate:latest --env production
            yarn knex seed:run --env production
            pm2 restart 'yarn start'
          host: 34.233.164.139
          username: ubuntu
          port: 22
          key: ${{secrets.SSH_PRIVATE_KEY}}
